### ISSUE TITLE
Specs are failing due to change in apostrophe

### ISSUE THREAD

**Issue by littleforest** [thoughtbot/art_vandelay#20]
Rails main has [changed the default apostrophe character](https://github.com/rails/rails/pull/45463), so some tests are now failing.

Not sure the best way to make this change -- is it okay to put a conditional in the test to check what version of Rails is being run?

```
Failure:
ArtVandelayTest::Import#test_returns_results [/home/runner/work/art_vandelay/art_vandelay/test/art_vandelay_test.rb:449]:
--- expected
+++ actual
@@ -1 +1 @@
-[{:row=>["invalid@example.com", nil], :errors=>{:***"can't be blank"]}}]
+[{:row=>["invalid@example.com", nil], :errors=>{:***"can’t be blank"]}}]
```

**Comment by stevepolitodesign** [comment]
Closed by #21
