### ISSUE TITLE
Would`art_vandelay` accept pull requests for a JSON adapter?

### ISSUE THREAD

**Issue by benjaminwil** [thoughtbot/art_vandelay#26]
Hi. Thanks for publishing this gem 🙏 

Currently this gem supports importing and exporting CSVs. If I were to implement a JSON adapter would you consider a pull request (or: pull requests) for this feature?

**Comment by stevepolitodesign** [comment]
I think a JSON adapter would be a nice addition, especially since it's already part of Ruby's Standard Library. Maybe that's the metric on which we determine if other adapters should be added or not. But for now, I say go for it 👍
